### ISSUE TITLE
Control.update_parameter() got an unexpected keyword argument 'event'

### ISSUE THREAD

**Issue by aseyq** [JoelForamitti/ipysimulate#1]
Hi there,

I am trying to reproduce the examples here: https://agentpy.readthedocs.io/en/latest/guide_interactive.html 

The widgets appear and work but when I attempt to change the parameters I get the following error:

```python
TypeError                                 Traceback (most recent call last)
File ~/.local/lib/python3.10/site-packages/ipysimulate/control.py:134, in Control._handle_button_msg(self, _, content, buffers)
    131 def _handle_button_msg(self, _, content, buffers):
    132     """ Handles messages from the front-end 
    133     by calling method of same name as msg. """
--> 134     getattr(self, content.get('event', ''))(**content)

TypeError: Control.update_parameter() got an unexpected keyword argument 'event'
```

And the parameters changes don't work. I am using the version `0.2.1` on Python 3.10.4

**Comment by aseyq** [comment]
My mistake. I think this was due to some old packages I had that were blocking the update of others. With a clean python installation/virtual environment, it works properly.

**Comment by jofmi** [comment]
Glad to hear!
